import {
  PhysicalRoom,
  RoomCategory,
  Guest,
  CRMBooking,
  GuestFolio,
  MenuItem,
  TransferRoute,
  RentalVehicle,
  TransportRequest,
  HousekeepingTask,
  Expense,
  StaffAccount,
  SeasonalDateRange,
  RoomSeasonalTariffs,
} from '@/types/crm';

export const INITIAL_ROOM_CATEGORIES: RoomCategory[] = [
  {
    id: 'cat-1',
    code: 'deluxe_mountain',
    name: 'Deluxe Mountain View with Balcony',
    description: 'Boutique rooms with private panoramic balconies facing snow-capped Himalayan sunrise peaks, king bed, and heated blankets.',
    basePriceWeekday: 4500,
    basePriceWeekend: 5200,
    baseAdults: 2,
    maxAdults: 3,
    maxChildren: 2,
    extraAdultCharge: 1200,
    extraChildCharge: 600,
    amenities: ['Private Mountain Balcony', 'Sunrise Vista', 'Starlink Wi-Fi', 'En-suite Rain Shower', 'Heated Blanket', 'Artisanal Tea Station'],
  },
  {
    id: 'cat-2',
    code: 'deluxe_forest',
    name: 'Deluxe Forest View with Balcony',
    description: 'Serene woodland retreat with private balcony immersed in pine tree canopy and birdsong, artisanal timber desk, and heated comforts.',
    basePriceWeekday: 4200,
    basePriceWeekend: 4800,
    baseAdults: 2,
    maxAdults: 2,
    maxChildren: 1,
    extraAdultCharge: 1200,
    extraChildCharge: 600,
    amenities: ['Private Pine Balcony', 'Forest Canopy View', 'Wood Workstation', 'Starlink Wi-Fi', 'Heated Blanket', 'Organic Toiletries'],
  },
  {
    id: 'cat-3',
    code: 'premium_suite',
    name: 'Premium Mountain View Suites',
    description: 'Grand top-floor suites with 180° panoramic observation balcony, artisanal fireplace, sitting lounge with daybed, and French press coffee.',
    basePriceWeekday: 6500,
    basePriceWeekend: 7500,
    baseAdults: 2,
    maxAdults: 4,
    maxChildren: 2,
    extraAdultCharge: 1500,
    extraChildCharge: 750,
    amenities: ['Panoramic Observation Balcony', 'Artisanal Fireplace', 'Lounge with Daybed', 'Starlink Wi-Fi', 'Luxury Rain Shower', 'Artisanal Coffee Bar'],
  },
];

export const INITIAL_PHYSICAL_ROOMS: PhysicalRoom[] = [
  {
    id: 'room-101',
    roomNumber: 101,
    name: 'Room 101 - Sunrise Mountain Balcony',
    categoryId: 'cat-1',
    categoryCode: 'deluxe_mountain',
    categoryName: 'Deluxe Mountain View with Balcony',
    floorLevel: 1,
    currentStatus: 'available',
    housekeeping: 'clean',
    qrSecretToken: 'wp-qr-room101-token99',
    notes: '',
  },
  {
    id: 'room-102',
    roomNumber: 102,
    name: 'Room 102 - Valley Vista Balcony',
    categoryId: 'cat-1',
    categoryCode: 'deluxe_mountain',
    categoryName: 'Deluxe Mountain View with Balcony',
    floorLevel: 1,
    currentStatus: 'available',
    housekeeping: 'clean',
    qrSecretToken: 'wp-qr-room102-token88',
    notes: '',
  },
  {
    id: 'room-103',
    roomNumber: 103,
    name: 'Room 103 - Himalayan Mist Balcony',
    categoryId: 'cat-1',
    categoryCode: 'deluxe_mountain',
    categoryName: 'Deluxe Mountain View with Balcony',
    floorLevel: 1,
    currentStatus: 'available',
    housekeeping: 'clean',
    qrSecretToken: 'wp-qr-room103-token77',
    notes: '',
  },
  {
    id: 'room-104',
    roomNumber: 104,
    name: 'Room 104 - Pine Canopy Balcony',
    categoryId: 'cat-2',
    categoryCode: 'deluxe_forest',
    categoryName: 'Deluxe Forest View with Balcony',
    floorLevel: 1,
    currentStatus: 'available',
    housekeeping: 'clean',
    qrSecretToken: 'wp-qr-room104-token66',
    notes: '',
  },
  {
    id: 'room-201',
    roomNumber: 201,
    name: 'Room 201 - Summit Observation Suite',
    categoryId: 'cat-3',
    categoryCode: 'premium_suite',
    categoryName: 'Premium Mountain View Suites',
    floorLevel: 2,
    currentStatus: 'available',
    housekeeping: 'clean',
    qrSecretToken: 'wp-qr-room201-token55',
    notes: '',
  },
  {
    id: 'room-202',
    roomNumber: 202,
    name: 'Room 202 - Kanchenjunga View Suite',
    categoryId: 'cat-3',
    categoryCode: 'premium_suite',
    categoryName: 'Premium Mountain View Suites',
    floorLevel: 2,
    currentStatus: 'available',
    housekeeping: 'clean',
    qrSecretToken: 'wp-qr-room202-token44',
    notes: '',
  },
  {
    id: 'room-203',
    roomNumber: 203,
    name: 'Room 203 - Cloud Peak Master Suite',
    categoryId: 'cat-3',
    categoryCode: 'premium_suite',
    categoryName: 'Premium Mountain View Suites',
    floorLevel: 2,
    currentStatus: 'available',
    housekeeping: 'clean',
    qrSecretToken: 'wp-qr-room203-token33',
    notes: '',
  },
];

export const INITIAL_GUESTS: Guest[] = [
  {
    id: 'gst-8101298882',
    fullName: 'Savera Guest',
    phone: '8101298882',
    email: 'guest8882@gmail.com',
    nationality: 'Indian',
    idType: 'Aadhaar Card',
    documentStatus: 'pending',
    totalLifetimeStays: 1,
  },
];

export const INITIAL_BOOKINGS: CRMBooking[] = [
  {
    id: 'bk-8101298882',
    bookingReference: 'SH-2K2609001',
    roomId: 'room-101',
    roomNumber: 101,
    roomName: 'Room 101 - Sunrise Mountain Balcony',
    guestId: 'gst-8101298882',
    guest: {
      id: 'gst-8101298882',
      fullName: 'Savera Guest',
      phone: '8101298882',
      email: 'guest8882@gmail.com',
      nationality: 'Indian',
      idType: 'Aadhaar Card',
      documentStatus: 'pending',
      totalLifetimeStays: 1,
    },
    checkInDate: new Date().toISOString().split('T')[0],
    checkOutDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    tapeStatus: 'confirmed',
    bookingStatus: 'confirmed',
    mealPlan: 'CP',
    adultsCount: 2,
    childrenCount: 0,
    roomRatePerNight: 4500,
    totalNights: 1,
    totalRoomAmount: 4500,
    specialRequests: 'Mountain sunrise view, warm drinking water',
    documentStatus: 'pending',
    advancePaid: 2000,
    advancePaymentMethod: 'upi',
  },
];

export const INITIAL_FOLIOS: GuestFolio[] = [
  {
    id: 'fol-8101298882',
    bookingId: 'bk-8101298882',
    guestId: 'gst-8101298882',
    guestName: 'Savera Guest',
    roomNumber: 101,
    roomName: 'Room 101 - Sunrise Mountain Balcony',
    folioNumber: 'FOL-2026-10188',
    status: 'open',
    totalRoomCharges: 4500,
    totalFbCharges: 0,
    totalAddonCharges: 0,
    totalTax: 225,
    discountAmount: 0,
    netPayable: 4725,
    totalPaid: 2000,
    balanceDue: 2725,
    charges: [
      {
        id: 'chg-8101298882-room',
        folioId: 'fol-8101298882',
        category: 'room_tariff',
        chargeStatus: 'posted',
        title: 'Stay Tariff: Room 101 - Sunrise Mountain Balcony (1 night @ ₹4,500/nt)',
        amount: 4500,
        sourceReferenceType: 'booking',
        sourceReferenceId: 'bk-8101298882',
        postedAt: new Date().toISOString(),
      },
    ],
    payments: [
      {
        id: 'pay-8101298882-adv',
        folioId: 'fol-8101298882',
        amount: 2000,
        paymentMethod: 'upi',
        receiptNotes: 'Advance deposit via UPI',
        collectedAt: new Date().toISOString(),
        collectedByName: 'Administrator',
      },
    ],
  },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    "id": "menu-tea-1",
    "categoryId": "bev-hot-teas",
    "categoryName": "Hot Teas",
    "name": "Darjeeling First Flush Tea (Pot)",
    "description": "Aromatic spring harvest single-estate Darjeeling tea brewed in a pot with delicate floral muscatel notes.",
    "price": 120,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 8,
    "imageUrl": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-tea-2",
    "categoryId": "bev-hot-teas",
    "categoryName": "Hot Teas",
    "name": "Darjeeling Second Flush Tea (Pot)",
    "description": "Full-bodied summer harvest Darjeeling tea brewed in a pot, rich amber liquor with distinct muscatel grape aroma.",
    "price": 100,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 8,
    "imageUrl": "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-tea-3",
    "categoryId": "bev-hot-teas",
    "categoryName": "Hot Teas",
    "name": "Green Tea",
    "description": "Pure soothing whole-leaf green tea rich in antioxidants, served with wildflower honey and lemon.",
    "price": 60,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 6,
    "imageUrl": "https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-tea-4",
    "categoryId": "bev-hot-teas",
    "categoryName": "Hot Teas",
    "name": "Darjeeling Black Tea (Cup)",
    "description": "Classic freshly brewed single cup of mountain black tea, crisp, amber, and revitalizing.",
    "price": 50,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 5,
    "imageUrl": "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-tea-5",
    "categoryId": "bev-hot-teas",
    "categoryName": "Hot Teas",
    "name": "Lemon Tea / Honey Lemon Tea",
    "description": "Fresh Darjeeling tea infused with squeezed hill lemon juice and optional pure raw honey.",
    "price": 50,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 5,
    "imageUrl": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-tea-6",
    "categoryId": "bev-hot-teas",
    "categoryName": "Hot Teas",
    "name": "Masala Chai",
    "description": "Traditional homestyle milk tea simmered with crushed hill ginger, green cardamom, cloves, and cinnamon.",
    "price": 40,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 8,
    "imageUrl": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-tea-7",
    "categoryId": "bev-hot-teas",
    "categoryName": "Hot Teas",
    "name": "Ginger / Cardamom Tea",
    "description": "Warm soothing mountain tea brewed with fresh crushed hill ginger root and fragrant cardamom.",
    "price": 40,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 8,
    "imageUrl": "https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-coffee-1",
    "categoryId": "bev-hot-coffees",
    "categoryName": "Hot Coffees",
    "name": "Mocha",
    "description": "Rich espresso combined with steamed milk and velvety dark cocoa, topped with smooth chocolate drizzle.",
    "price": 130,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 10,
    "imageUrl": "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-coffee-2",
    "categoryId": "bev-hot-coffees",
    "categoryName": "Hot Coffees",
    "name": "Café Latte",
    "description": "Smooth double shot of dark roast espresso poured into creamy steamed milk with light micro-foam.",
    "price": 120,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 8,
    "imageUrl": "https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-coffee-3",
    "categoryId": "bev-hot-coffees",
    "categoryName": "Hot Coffees",
    "name": "Cappuccino",
    "description": "Balanced espresso layered with equal parts steamed milk and thick velvety milk foam dusted with cocoa.",
    "price": 110,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 8,
    "imageUrl": "https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-coffee-4",
    "categoryId": "bev-hot-coffees",
    "categoryName": "Hot Coffees",
    "name": "Black Coffee / Americano",
    "description": "Bold dark roast espresso lengthened with steaming mountain spring water for a clean, robust flavor.",
    "price": 70,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 6,
    "imageUrl": "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-coffee-5",
    "categoryId": "bev-hot-coffees",
    "categoryName": "Hot Coffees",
    "name": "Espresso",
    "description": "Intense single shot of freshly ground Arabica beans topped with rich golden-brown crema.",
    "price": 70,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 5,
    "imageUrl": "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-coffee-6",
    "categoryId": "bev-hot-coffees",
    "categoryName": "Hot Coffees",
    "name": "Hot Coffee (Milk)",
    "description": "Homestyle whipped beaten coffee hand-frothed with hot dairy milk and sugar.",
    "price": 60,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 6,
    "imageUrl": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-cold-1",
    "categoryId": "bev-cold",
    "categoryName": "Cold Beverages",
    "name": "Cold Coffee with Ice Cream",
    "description": "Thick blended iced espresso shake crowned with a rich scoop of velvety vanilla ice cream.",
    "price": 140,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 8,
    "imageUrl": "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-cold-2",
    "categoryId": "bev-cold",
    "categoryName": "Cold Beverages",
    "name": "Cold Coffee",
    "description": "Classic creamy iced coffee blended with espresso, cold milk, and chocolate syrup.",
    "price": 110,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 6,
    "imageUrl": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-cold-3",
    "categoryId": "bev-cold",
    "categoryName": "Cold Beverages",
    "name": "Iced Tea (Lemon / Peach)",
    "description": "Chilled artisanal Darjeeling black tea served on the rocks with citrus lemon or juicy peach infusion.",
    "price": 90,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 6,
    "imageUrl": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-cold-4",
    "categoryId": "bev-cold",
    "categoryName": "Cold Beverages",
    "name": "Fruit Juice (Apple, Mix)",
    "description": "Refreshing glass of wholesome fruit juice (Crisp Himalayan Apple or Tropical Mixed Fruit).",
    "price": 60,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 5,
    "imageUrl": "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-cold-5",
    "categoryId": "bev-cold",
    "categoryName": "Cold Beverages",
    "name": "Masala Lemonade",
    "description": "Sparkling lemon cooler flavored with roasted cumin seeds, Himalayan black salt, and fresh mint.",
    "price": 50,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 5,
    "imageUrl": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-cold-6",
    "categoryId": "bev-cold",
    "categoryName": "Cold Beverages",
    "name": "Cold Drink (200ml) / Frooti / Maazza",
    "description": "Chilled bottled soft drink (200ml) or sweet mango juice (Frooti / Maaza).",
    "price": 25,
    "itemType": "beverage",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 2,
    "imageUrl": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-1",
    "categoryId": "bf-veg",
    "categoryName": "Breakfast (Vegetarian)",
    "name": "Cheese Sandwich",
    "description": "Golden grilled sandwich packed with gooey processed cheese, subtle herbs, and mild capsicum.",
    "price": 110,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 12,
    "imageUrl": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-2",
    "categoryId": "bf-veg",
    "categoryName": "Breakfast (Vegetarian)",
    "name": "Parantha Sabji",
    "description": "Two flaky, layered whole-wheat paranthas served with homestyle spiced potato-vegetable sabji and pickle.",
    "price": 90,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-3",
    "categoryId": "bf-veg",
    "categoryName": "Breakfast (Vegetarian)",
    "name": "Puri Sabji",
    "description": "Piping hot golden puffed puris (4 pcs) served with traditional spiced potato aloo rasedar gravy and achar.",
    "price": 80,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-4",
    "categoryId": "bf-veg",
    "categoryName": "Breakfast (Vegetarian)",
    "name": "Roti Sabji",
    "description": "Four freshly rolled soft tawa phulkas served with fresh seasonal vegetable sabji and pickled chillies.",
    "price": 80,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 15,
    "imageUrl": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-5",
    "categoryId": "bf-veg",
    "categoryName": "Breakfast (Vegetarian)",
    "name": "Veg Sandwich",
    "description": "Fresh toasted or plain bread filled with crisp cucumber, juicy tomatoes, onions, and tangy mint spread.",
    "price": 80,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 10,
    "imageUrl": "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-6",
    "categoryId": "bf-veg",
    "categoryName": "Breakfast (Vegetarian)",
    "name": "Cornflakes",
    "description": "Crisp golden toasted corn cereal served with warm or chilled dairy milk, accompanied by sugar or honey.",
    "price": 80,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 5,
    "imageUrl": "https://images.unsplash.com/photo-1588710929895-8854890d70b7?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-7",
    "categoryId": "bf-veg",
    "categoryName": "Breakfast (Vegetarian)",
    "name": "Gobi Parantha",
    "description": "Crispy whole wheat tawa parantha stuffed with seasoned grated cauliflower, fresh ginger, and green chillies.",
    "price": 70,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-8",
    "categoryId": "bf-veg",
    "categoryName": "Breakfast (Vegetarian)",
    "name": "Aloo Parantha",
    "description": "Hearty tawa parantha filled with spiced mashed potatoes, roasted cumin, and cilantro, served with butter & pickle.",
    "price": 60,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 18,
    "imageUrl": "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-9",
    "categoryId": "bf-veg",
    "categoryName": "Breakfast (Vegetarian)",
    "name": "Butter Toast with Masala Chai",
    "description": "Crisp buttered golden toast (2 slices) served alongside a hot, steaming cup of aromatic masala chai.",
    "price": 60,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 10,
    "imageUrl": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-10",
    "categoryId": "bf-veg",
    "categoryName": "Breakfast (Vegetarian)",
    "name": "Plain Parantha",
    "description": "Flaky layered whole-wheat triangular tawa parantha cooked in ghee, served with pickle.",
    "price": 40,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 12,
    "imageUrl": "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-11",
    "categoryId": "bf-veg",
    "categoryName": "Breakfast (Vegetarian)",
    "name": "Bread Jam",
    "description": "Two slices of freshly toasted bread generously smeared with sweet mixed fruit jam.",
    "price": 40,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 5,
    "imageUrl": "https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-egg-1",
    "categoryId": "bf-egg",
    "categoryName": "Breakfast (Egg Signatures)",
    "name": "Egg Parantha",
    "description": "Golden tawa parantha enveloped with a seasoned beaten egg, chopped onions, and green chillies.",
    "price": 80,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 15,
    "imageUrl": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-egg-2",
    "categoryId": "bf-egg",
    "categoryName": "Breakfast (Egg Signatures)",
    "name": "Bread Omelet",
    "description": "Classic hill station street-style omelet cooked with diced onions and herbs, wrapped around toasted bread slices.",
    "price": 70,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 12,
    "imageUrl": "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bf-egg-3",
    "categoryId": "bf-egg",
    "categoryName": "Breakfast (Egg Signatures)",
    "name": "Double Omelet",
    "description": "Two farm-fresh eggs whisked with onions, green chillies, and mountain herbs, cooked fluffy on a hot skillet.",
    "price": 60,
    "itemType": "breakfast",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 10,
    "imageUrl": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-snack-veg-1",
    "categoryId": "snack-veg",
    "categoryName": "Vegetarian Quick Bites",
    "name": "Paneer Pakora",
    "description": "Thick batons of cottage cheese coated in spiced chickpea batter and deep-fried till golden and crisp.",
    "price": 130,
    "itemType": "snack",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 18,
    "imageUrl": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-snack-veg-2",
    "categoryId": "snack-veg",
    "categoryName": "Vegetarian Quick Bites",
    "name": "Veg Pakora",
    "description": "Assorted seasonal vegetable fritters (potatoes, onions, spinach) fried in herb-spiced besan batter.",
    "price": 90,
    "itemType": "snack",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 15,
    "imageUrl": "https://images.unsplash.com/photo-1567184108861-12799fa778bf?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-snack-veg-3",
    "categoryId": "snack-veg",
    "categoryName": "Vegetarian Quick Bites",
    "name": "Veg Roll",
    "description": "Crisp parantha rolled with crunchy julienned cabbage, bell peppers, carrots, onions, and zesty sauces.",
    "price": 90,
    "itemType": "snack",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 15,
    "imageUrl": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-snack-veg-4",
    "categoryId": "snack-veg",
    "categoryName": "Vegetarian Quick Bites",
    "name": "Veg Soup / Tomato Soup",
    "description": "Steaming hot bowl of hearty garden vegetable soup or creamy rich tomato soup with garlic butter croutons.",
    "price": 90,
    "itemType": "snack",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 15,
    "imageUrl": "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-snack-veg-5",
    "categoryId": "snack-veg",
    "categoryName": "Vegetarian Quick Bites",
    "name": "Veg Maggi",
    "description": "All-time favorite instant mountain noodles prepared with sautéed onions, tomatoes, green peas, and spices.",
    "price": 50,
    "itemType": "snack",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 10,
    "imageUrl": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-snack-nv-1",
    "categoryId": "snack-nonveg",
    "categoryName": "Non-Vegetarian Quick Bites",
    "name": "Chicken Roll",
    "description": "Fresh parantha wrapped around succulent diced chicken pieces sautéed with onions, chillies, and tangy sauces.",
    "price": 110,
    "itemType": "snack",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 18,
    "imageUrl": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-snack-nv-2",
    "categoryId": "snack-nonveg",
    "categoryName": "Non-Vegetarian Quick Bites",
    "name": "Egg Maggi",
    "description": "Hot steaming noodles tossed with scrambled farm egg, finely chopped onions, and special tastemaker herbs.",
    "price": 70,
    "itemType": "snack",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 12,
    "imageUrl": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-snack-himalayan-1",
    "categoryId": "snack-indo-himalayan",
    "categoryName": "Indo-Chinese & Himalayan",
    "name": "Egg Fried Rice",
    "description": "Wok-tossed basmati rice with fluffy scrambled eggs, diced carrots, beans, scallions, and soy sauce.",
    "price": 140,
    "itemType": "snack",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-snack-himalayan-2",
    "categoryId": "snack-indo-himalayan",
    "categoryName": "Indo-Chinese & Himalayan",
    "name": "Veg Thukpa",
    "description": "Comforting Tibetan noodle soup loaded with seasonal vegetables in an aromatic ginger-garlic broth.",
    "price": 120,
    "itemType": "snack",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-snack-himalayan-3",
    "categoryId": "snack-indo-himalayan",
    "categoryName": "Indo-Chinese & Himalayan",
    "name": "Veg Fried Rice",
    "description": "Fragrant long-grain rice stir-fried in a smoking wok with finely chopped farm vegetables and soy seasoning.",
    "price": 120,
    "itemType": "snack",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-snack-himalayan-4",
    "categoryId": "snack-indo-himalayan",
    "categoryName": "Indo-Chinese & Himalayan",
    "name": "Veg Noodles",
    "description": "Classic Hakka-style noodles stir-fried with shredded cabbage, bell peppers, carrots, and spring onions.",
    "price": 110,
    "itemType": "snack",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 18,
    "imageUrl": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-snack-himalayan-5",
    "categoryId": "snack-indo-himalayan",
    "categoryName": "Indo-Chinese & Himalayan",
    "name": "Veg Momos",
    "description": "Authentic handmade steamed dumplings stuffed with cabbage, paneer, and herbs. Served with spicy dalle chutney.",
    "price": 90,
    "itemType": "snack",
    "isAvailable": true,
    "isLateNightEligible": true,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-paneer-1",
    "categoryId": "main-paneer",
    "categoryName": "Paneer Specialties",
    "name": "Paneer Butter Masala",
    "description": "Soft cottage cheese cubes cooked in a silky, mildly sweet tomato-cashew and cream gravy with butter.",
    "price": 190,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 25,
    "imageUrl": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-paneer-2",
    "categoryId": "main-paneer",
    "categoryName": "Paneer Specialties",
    "name": "Paneer Shahi",
    "description": "Royal preparation of fresh paneer in a fragrant, creamy white cashew-nut gravy flavored with cardamom.",
    "price": 180,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 25,
    "imageUrl": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-paneer-3",
    "categoryId": "main-paneer",
    "categoryName": "Paneer Specialties",
    "name": "Paneer Do Pyaza",
    "description": "Paneer cubes braised with double the quantity of onions—caramelized in gravy and crunchy sautéed petals.",
    "price": 180,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 25,
    "imageUrl": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-paneer-4",
    "categoryId": "main-paneer",
    "categoryName": "Paneer Specialties",
    "name": "Paneer Kadai",
    "description": "Cottage cheese pieces wok-tossed with crunchy bell peppers, onions, and freshly ground coriander-kadai spice blend.",
    "price": 180,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 25,
    "imageUrl": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-paneer-5",
    "categoryId": "main-paneer",
    "categoryName": "Paneer Specialties",
    "name": "Desi Paneer",
    "description": "Rustic homestyle paneer curry cooked with stone-ground hill spices, mustard oil, tomatoes, and fresh coriander.",
    "price": 170,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 22,
    "imageUrl": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-veg-1",
    "categoryId": "main-veg",
    "categoryName": "Vegetarian Curries & Vegetables",
    "name": "Mushroom Sabji",
    "description": "Fresh plump mushrooms sautéed with garden green peas in a rich spiced onion-tomato masala gravy.",
    "price": 160,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 22,
    "imageUrl": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-veg-2",
    "categoryId": "main-veg",
    "categoryName": "Vegetarian Curries & Vegetables",
    "name": "Veg Kofta",
    "description": "Handcrafted spiced vegetable and paneer dumplings gently simmered in a luscious creamy tomato-onion gravy.",
    "price": 140,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 25,
    "imageUrl": "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-veg-3",
    "categoryId": "main-veg",
    "categoryName": "Vegetarian Curries & Vegetables",
    "name": "Mix Veg",
    "description": "Seasonal assortment of cauliflower florets, carrots, french beans, and green peas tossed in a fragrant masala.",
    "price": 120,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-veg-4",
    "categoryId": "main-veg",
    "categoryName": "Vegetarian Curries & Vegetables",
    "name": "Nepali Aloo Dum",
    "description": "Traditional Darjeeling-Nepali style spicy potato curry cooked with mustard oil, fenugreek, and fiery dalle chilli.",
    "price": 110,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-veg-5",
    "categoryId": "main-veg",
    "categoryName": "Vegetarian Curries & Vegetables",
    "name": "Aloo Matar",
    "description": "Classic comforting North Indian curry of tender potatoes and sweet green peas in an aromatic tomato gravy.",
    "price": 110,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-veg-6",
    "categoryId": "main-veg",
    "categoryName": "Vegetarian Curries & Vegetables",
    "name": "Aloo Gobi",
    "description": "Dry homestyle stir-fry of crisp cauliflower florets and tender potatoes tempered with cumin seeds and ginger.",
    "price": 110,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-veg-7",
    "categoryId": "main-veg",
    "categoryName": "Vegetarian Curries & Vegetables",
    "name": "Kadhi Pakora",
    "description": "Slow-simmered tangy yogurt and gram flour stew studded with crispy onion pakoras and tempered with mustard seeds.",
    "price": 110,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 25,
    "imageUrl": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-veg-8",
    "categoryId": "main-veg",
    "categoryName": "Vegetarian Curries & Vegetables",
    "name": "Aloo Dum",
    "description": "Slow-braised baby potatoes cooked in a deeply flavored onion-tomato gravy with roasted ground spices.",
    "price": 100,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 18,
    "imageUrl": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-veg-9",
    "categoryId": "main-veg",
    "categoryName": "Vegetarian Curries & Vegetables",
    "name": "Aloo Jeera",
    "description": "Diced potatoes sautéed with roasted cumin seeds, turmeric, green chillies, and fresh chopped coriander.",
    "price": 100,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 15,
    "imageUrl": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-dal-1",
    "categoryId": "main-dal",
    "categoryName": "Dal & Legumes",
    "name": "Dal Tadka",
    "description": "Yellow lentils slow-cooked and tempered with sizzling desi ghee, cumin seeds, garlic, and dried red chillies.",
    "price": 120,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1546833998-877b37c2e5c4?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-dal-2",
    "categoryId": "main-dal",
    "categoryName": "Dal & Legumes",
    "name": "Chana Masala",
    "description": "White chickpeas simmered with roasted spices, amchur, ginger juliennes, and tomatoes into a rich gravy.",
    "price": 120,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 22,
    "imageUrl": "https://images.unsplash.com/photo-1546833998-877b37c2e5c4?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-dal-3",
    "categoryId": "main-dal",
    "categoryName": "Dal & Legumes",
    "name": "Rajma",
    "description": "Mountain kidney beans slow-cooked with fresh onion-tomato paste, whole spices, and butter to a luscious stew.",
    "price": 110,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 25,
    "imageUrl": "https://images.unsplash.com/photo-1546833998-877b37c2e5c4?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-dal-4",
    "categoryId": "main-dal",
    "categoryName": "Dal & Legumes",
    "name": "Mix Dal",
    "description": "Nutritious homestyle harmony of five hill pulses cooked with turmeric and tempered with hing, garlic, and cumin.",
    "price": 110,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1546833998-877b37c2e5c4?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-dal-5",
    "categoryId": "main-dal",
    "categoryName": "Dal & Legumes",
    "name": "Plain Dal",
    "description": "Light, comforting yellow lentil soup tempered gently with turmeric, salt, and mild cumin seeds.",
    "price": 80,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 15,
    "imageUrl": "https://images.unsplash.com/photo-1546833998-877b37c2e5c4?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-nv-1",
    "categoryId": "main-nonveg",
    "categoryName": "Non-Vegetarian",
    "name": "Chicken Roast",
    "description": "Tender bone-in chicken marinated in mountain spices, pan-roasted to perfection with caramelized onion gravy.",
    "price": 220,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 30,
    "imageUrl": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-main-nv-2",
    "categoryId": "main-nonveg",
    "categoryName": "Non-Vegetarian",
    "name": "Chicken Kadhai",
    "description": "Chicken pieces cooked in an iron wok with bell peppers, crushed coriander seeds, ginger, and spicy masala.",
    "price": 220,
    "itemType": "main",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 30,
    "imageUrl": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-thali-1",
    "categoryId": "thali",
    "categoryName": "Thalis (Set Meals)",
    "name": "Fish Thali",
    "description": "Complete regional platter featuring homestyle Fish Curry, Steamed Rice, 2 Rotis, Dal, Seasonal Sabji, Salad & Papad.",
    "price": 240,
    "itemType": "thali",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 30,
    "imageUrl": "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-thali-2",
    "categoryId": "thali",
    "categoryName": "Thalis (Set Meals)",
    "name": "Chicken Thali",
    "description": "Wholesome hearty platter with Chicken Curry, Fragrant Rice, 2 Soft Rotis, Dal Tadka, Seasonal Sabji, Salad & Achar.",
    "price": 220,
    "itemType": "thali",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 30,
    "imageUrl": "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-thali-3",
    "categoryId": "thali",
    "categoryName": "Thalis (Set Meals)",
    "name": "Paneer Thali",
    "description": "Rich vegetarian feast served with Paneer Butter Masala, Steamed Rice, 2 Rotis, Dal Tadka, Seasonal Sabji, Raita & Papad.",
    "price": 180,
    "itemType": "thali",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 25,
    "imageUrl": "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-thali-4",
    "categoryId": "thali",
    "categoryName": "Thalis (Set Meals)",
    "name": "Veg Thali",
    "description": "Traditional daily homestay meal with Daily Sabji, Dal Tadka, Steamed Rice, 2 Rotis, Fresh Salad, and Homemade Pickle.",
    "price": 150,
    "itemType": "thali",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 25,
    "imageUrl": "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-rice-1",
    "categoryId": "rice-breads",
    "categoryName": "Rice & Indian Breads",
    "name": "Veg Pulao",
    "description": "Aromatic long-grain basmati rice cooked with whole hill spices, green peas, diced carrots, and pure ghee.",
    "price": 130,
    "itemType": "sides",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 20,
    "imageUrl": "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-rice-2",
    "categoryId": "rice-breads",
    "categoryName": "Rice & Indian Breads",
    "name": "Jeera Rice",
    "description": "Fluffy basmati rice tempered in pure ghee with roasted cumin seeds and fresh green coriander.",
    "price": 90,
    "itemType": "sides",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 15,
    "imageUrl": "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-rice-3",
    "categoryId": "rice-breads",
    "categoryName": "Rice & Indian Breads",
    "name": "Plain Rice",
    "description": "Piping hot steamed long-grain white rice, light and fluffy.",
    "price": 50,
    "itemType": "sides",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 12,
    "imageUrl": "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bread-1",
    "categoryId": "rice-breads",
    "categoryName": "Rice & Indian Breads",
    "name": "Butter Roti",
    "description": "Fresh puffed whole-wheat phulka roasted on open flame and brushed generously with desi butter.",
    "price": 20,
    "itemType": "sides",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 8,
    "imageUrl": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-bread-2",
    "categoryId": "rice-breads",
    "categoryName": "Rice & Indian Breads",
    "name": "Plain Roti",
    "description": "Soft, light whole-wheat tawa phulka roasted dry without butter or oil.",
    "price": 15,
    "itemType": "sides",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 8,
    "imageUrl": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-side-1",
    "categoryId": "sides-acc",
    "categoryName": "Sides",
    "name": "Raita",
    "description": "Chilled whipped yogurt seasoned with roasted cumin powder, black salt, and finely diced cucumber.",
    "price": 50,
    "itemType": "sides",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 6,
    "imageUrl": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-side-2",
    "categoryId": "sides-acc",
    "categoryName": "Sides",
    "name": "Salad",
    "description": "Freshly sliced crunchy cucumber, juicy tomatoes, onion rings, fresh lemon wedge, and green chillies.",
    "price": 40,
    "itemType": "sides",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 5,
    "imageUrl": "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-side-3",
    "categoryId": "sides-acc",
    "categoryName": "Sides",
    "name": "Dahi",
    "description": "Bowl of fresh set homestyle dairy curd, cool, smooth, and naturally rich.",
    "price": 30,
    "itemType": "sides",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 3,
    "imageUrl": "https://images.unsplash.com/photo-1571212515416-fef01fc43637?auto=format&fit=crop&w=400&q=80"
  },
  {
    "id": "menu-side-4",
    "categoryId": "sides-acc",
    "categoryName": "Sides",
    "name": "Papad",
    "description": "Crispy roasted or fried lentil papad with mild chaat masala sprinkle.",
    "price": 15,
    "itemType": "sides",
    "isAvailable": true,
    "isLateNightEligible": false,
    "prepTimeMinutes": 3,
    "imageUrl": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=400&q=80"
  }
];

export const INITIAL_TRANSFER_ROUTES: TransferRoute[] = [
  {
    id: 'route-1',
    title: 'Darjeeling to NJP Railway Station / Bagdogra Airport (IXB)',
    origin: 'Savera Homestay, Darjeeling',
    destination: 'NJP Railway Station or Bagdogra Airport',
    priceWagonR: 3500,
    priceSedan: 4200,
    priceSUV: 5500,
    estimatedDurationHours: 3.5,
    isActive: true,
    seasonalTariffs: {
      season: { priceWagonR: 4200, priceSedan: 5000, priceSUV: 6500 },
      offSeason: { priceWagonR: 3000, priceSedan: 3600, priceSUV: 4800 },
    },
    modifiers: [
      {
        id: 'mod-1',
        routeId: 'route-1',
        name: 'Via Mirik Lake, Pine Forest & Sumendu Lake Promenade',
        extraCharge: 1500,
        extraDurationHours: 2.5,
      },
      {
        id: 'mod-2',
        routeId: 'route-1',
        name: 'Via Kurseong Eagle\'s Crag & Makaibari Tea Garden Tasting',
        extraCharge: 1200,
        extraDurationHours: 2.0,
      },
    ],
  },
  {
    id: 'route-2',
    title: 'Darjeeling to Gangtok (Sikkim)',
    origin: 'Savera Homestay, Darjeeling',
    destination: 'Gangtok Hotel / MG Marg',
    priceWagonR: 4800,
    priceSedan: 5600,
    priceSUV: 7200,
    estimatedDurationHours: 4.5,
    isActive: true,
    seasonalTariffs: {
      season: { priceWagonR: 5600, priceSedan: 6500, priceSUV: 8400 },
      offSeason: { priceWagonR: 4200, priceSedan: 4900, priceSUV: 6200 },
    },
    modifiers: [
      {
        id: 'mod-3',
        routeId: 'route-2',
        name: 'Via Namchi Char Dham & Ravangla Buddha Park Heritage Tour',
        extraCharge: 2200,
        extraDurationHours: 3.0,
      },
      {
        id: 'mod-4',
        routeId: 'route-2',
        name: 'Via Teesta River Confluence & Lovers Meet Viewpoint',
        extraCharge: 900,
        extraDurationHours: 1.5,
      },
    ],
  },
  {
    id: 'route-3',
    title: 'Darjeeling Full Day Heritage Sightseeing (Tiger Hill & Tea Gardens)',
    origin: 'Savera Homestay, Darjeeling',
    destination: 'Tiger Hill, Batasia Loop, Ghoom Monastery & Happy Valley',
    priceWagonR: 2800,
    priceSedan: 3400,
    priceSUV: 4500,
    estimatedDurationHours: 6.0,
    isActive: true,
    seasonalTariffs: {
      season: { priceWagonR: 3400, priceSedan: 4000, priceSUV: 5200 },
      offSeason: { priceWagonR: 2400, priceSedan: 2900, priceSUV: 3800 },
    },
    modifiers: [
      {
        id: 'mod-5',
        routeId: 'route-3',
        name: 'Add Himalayan Mountaineering Institute (HMI) & Zoo',
        extraCharge: 600,
        extraDurationHours: 1.5,
      },
      {
        id: 'mod-6',
        routeId: 'route-3',
        name: 'Add Japanese Peace Pagoda & Rock Garden Vista',
        extraCharge: 800,
        extraDurationHours: 2.0,
      },
    ],
  },
];

export const INITIAL_RENTAL_VEHICLES: RentalVehicle[] = [
  {
    id: 'veh-1',
    vehicleName: 'Royal Enfield Classic 350 (Stealth Black)',
    vehicleType: 'bike',
    ratePerDay: 1800,
    depositRequired: 2000,
    isAvailable: true,
    specs: '349cc J-Series Engine • Dual-Channel ABS • USB Port • Hill Torque',
    imageUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=600&q=80',
    seasonalTariffs: {
      seasonRatePerDay: 2200,
      offSeasonRatePerDay: 1500,
    },
  },
  {
    id: 'veh-2',
    vehicleName: 'Royal Enfield Himalayan 450 (Kamet White)',
    vehicleType: 'bike',
    ratePerDay: 2200,
    depositRequired: 2500,
    isAvailable: true,
    specs: '452cc Sherpa Liquid-Cooled • Long Travel Suspension • Ride-by-Wire • High Clearance',
    imageUrl: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=600&q=80',
    seasonalTariffs: {
      seasonRatePerDay: 2600,
      offSeasonRatePerDay: 1900,
    },
  },
  {
    id: 'veh-3',
    vehicleName: 'Honda Activa 6G (Matte Axis Grey)',
    vehicleType: 'scooty',
    ratePerDay: 900,
    depositRequired: 1000,
    isAvailable: true,
    specs: '110cc PGM-FI Engine • Telescopic Suspension • Combi Brake System • Lightweight City Commuter',
    imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80',
    seasonalTariffs: {
      seasonRatePerDay: 1100,
      offSeasonRatePerDay: 750,
    },
  },
];

export const INITIAL_DISPATCH_REQUESTS: TransportRequest[] = [];

export const INITIAL_HOUSEKEEPING_TASKS: HousekeepingTask[] = [];

export const INITIAL_FOOD_ORDERS: any[] = [];

export const INITIAL_EXPENSES: Expense[] = [];

export const INITIAL_STAFF_ACCOUNTS: StaffAccount[] = [
  {
    id: 'staff-admin',
    email: 'admin@saverahomestay.com',
    password: 'admin123',
    fullName: 'Savera Admin (Owner)',
    phone: '+91 81012 98882',
    role: 'admin',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
];


export const INITIAL_SEASONAL_DATE_RANGES: SeasonalDateRange[] = [
  {
    id: 'season-1',
    name: 'Summer Peak Holidays 2026',
    seasonType: 'season',
    startDate: '2026-05-01',
    endDate: '2026-06-30',
    description: 'High summer demand, warm mountain days and crisp evenings.',
  },
  {
    id: 'season-2',
    name: 'Autumn & Durga Puja / Diwali Peak',
    seasonType: 'season',
    startDate: '2026-10-01',
    endDate: '2026-11-15',
    description: 'Festive mountain holiday season with crystal clear Himalayan views.',
  },
  {
    id: 'season-3',
    name: 'Christmas & New Year Gala Peak',
    seasonType: 'season',
    startDate: '2026-12-20',
    endDate: '2027-01-05',
    description: 'Winter festive peak with live bonfires and celebration dinners.',
  },
  {
    id: 'season-4',
    name: 'Monsoon Green Season (Off-Season)',
    seasonType: 'off_season',
    startDate: '2026-07-15',
    endDate: '2026-08-31',
    description: 'Lush greenery, misty mountain waterfalls with relaxing discounted tariffs.',
  },
  {
    id: 'season-5',
    name: 'Post-Winter Lean Period (Off-Season)',
    seasonType: 'off_season',
    startDate: '2026-01-15',
    endDate: '2026-02-28',
    description: 'Quiet workation and budget solitude retreat months.',
  },
];

export const INITIAL_ROOM_SEASONAL_TARIFFS: Record<string, RoomSeasonalTariffs> = {
  // Website Room Categories
  'room-cat-1': {
    regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 },
    season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 },
    offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 },
    weekendSurchargePercent: 10,
    extraAdultRate: 1200,
    extraChildRate: 600,
  },
  'room-cat-2': {
    regular: { EP: 4200, CP: 4800, MAP: 5800, AP: 6800 },
    season: { EP: 5400, CP: 6100, MAP: 7200, AP: 8300 },
    offSeason: { EP: 3500, CP: 4000, MAP: 4800, AP: 5600 },
    weekendSurchargePercent: 10,
    extraAdultRate: 1200,
    extraChildRate: 600,
  },
  'room-cat-3': {
    regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 },
    season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 },
    offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 },
    weekendSurchargePercent: 12,
    extraAdultRate: 1500,
    extraChildRate: 750,
  },

  // Deluxe Mountain View with Balcony (Rooms 101, 102, 103)
  'room-101': {
    regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 },
    season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 },
    offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 },
    weekendSurchargePercent: 10,
    extraAdultRate: 1200,
    extraChildRate: 600,
  },
  'room-102': {
    regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 },
    season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 },
    offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 },
    weekendSurchargePercent: 10,
    extraAdultRate: 1200,
    extraChildRate: 600,
  },
  'room-103': {
    regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 },
    season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 },
    offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 },
    weekendSurchargePercent: 10,
    extraAdultRate: 1200,
    extraChildRate: 600,
  },

  // Deluxe Forest View with Balcony (Room 104)
  'room-104': {
    regular: { EP: 4200, CP: 4800, MAP: 5800, AP: 6800 },
    season: { EP: 5400, CP: 6100, MAP: 7200, AP: 8300 },
    offSeason: { EP: 3500, CP: 4000, MAP: 4800, AP: 5600 },
    weekendSurchargePercent: 10,
    extraAdultRate: 1200,
    extraChildRate: 600,
  },

  // Premium Mountain View Suites (Rooms 201, 202, 203)
  'room-201': {
    regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 },
    season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 },
    offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 },
    weekendSurchargePercent: 12,
    extraAdultRate: 1500,
    extraChildRate: 750,
  },
  'room-202': {
    regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 },
    season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 },
    offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 },
    weekendSurchargePercent: 12,
    extraAdultRate: 1500,
    extraChildRate: 750,
  },
  'room-203': {
    regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 },
    season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 },
    offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 },
    weekendSurchargePercent: 12,
    extraAdultRate: 1500,
    extraChildRate: 750,
  },

  // Fallbacks for legacy references
  'room-1': { regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 }, season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 }, offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 }, weekendSurchargePercent: 10 },
  'room-2': { regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 }, season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 }, offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 }, weekendSurchargePercent: 10 },
  'room-3': { regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 }, season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 }, offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 }, weekendSurchargePercent: 10 },
  'room-4': { regular: { EP: 4200, CP: 4800, MAP: 5800, AP: 6800 }, season: { EP: 5400, CP: 6100, MAP: 7200, AP: 8300 }, offSeason: { EP: 3500, CP: 4000, MAP: 4800, AP: 5600 }, weekendSurchargePercent: 10 },
  'room-5': { regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 }, season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 }, offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 }, weekendSurchargePercent: 12 },
  'room-6': { regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 }, season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 }, offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 }, weekendSurchargePercent: 12 },
  'room-7': { regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 }, season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 }, offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 }, weekendSurchargePercent: 12 },
};

