import {
  PhysicalRoom,
  RoomCategory,
  Guest,
  CRMBooking,
  GuestFolio,
  MenuItem,
  TransferRoute,
  RentalVehicle,
  TransportRequest,
  HousekeepingTask,
  Expense,
  StaffAccount,
  SeasonalDateRange,
  RoomSeasonalTariffs,
} from '@/types/crm';

export const INITIAL_ROOM_CATEGORIES: RoomCategory[] = [
  {
    id: 'cat-1',
    code: 'deluxe_mountain',
    name: 'Deluxe Mountain View with Balcony',
    description: 'Boutique rooms with private panoramic balconies facing snow-capped Himalayan sunrise peaks, king bed, and heated blankets.',
    basePriceWeekday: 4500,
    basePriceWeekend: 5200,
    maxAdults: 2,
    maxChildren: 1,
    amenities: ['Private Mountain Balcony', 'Sunrise Vista', 'Starlink Wi-Fi', 'En-suite Rain Shower', 'Heated Blanket', 'Artisanal Tea Station'],
  },
  {
    id: 'cat-2',
    code: 'deluxe_forest',
    name: 'Deluxe Forest View with Balcony',
    description: 'Serene woodland retreat with private balcony immersed in pine tree canopy and birdsong, artisanal timber desk, and heated comforts.',
    basePriceWeekday: 4200,
    basePriceWeekend: 4800,
    maxAdults: 2,
    maxChildren: 0,
    amenities: ['Private Pine Balcony', 'Forest Canopy View', 'Wood Workstation', 'Starlink Wi-Fi', 'Heated Blanket', 'Organic Toiletries'],
  },
  {
    id: 'cat-3',
    code: 'premium_suite',
    name: 'Premium Mountain View Suites',
    description: 'Grand top-floor suites with 180° panoramic observation balcony, artisanal fireplace, sitting lounge with daybed, and French press coffee.',
    basePriceWeekday: 6500,
    basePriceWeekend: 7500,
    maxAdults: 3,
    maxChildren: 1,
    amenities: ['Panoramic Observation Balcony', 'Artisanal Fireplace', 'Lounge with Daybed', 'Starlink Wi-Fi', 'Luxury Rain Shower', 'Artisanal Coffee Bar'],
  },
];

export const INITIAL_PHYSICAL_ROOMS: PhysicalRoom[] = [
  {
    id: 'room-101',
    roomNumber: 101,
    name: 'Room 101 - Sunrise Mountain Balcony',
    categoryId: 'cat-1',
    categoryCode: 'deluxe_mountain',
    categoryName: 'Deluxe Mountain View with Balcony',
    floorLevel: 1,
    currentStatus: 'checked_in',
    housekeeping: 'clean',
    qrSecretToken: 'wp-qr-room101-token99',
    notes: 'East wing sunrise view. Honeymooners, extra duvet provided.',
  },
  {
    id: 'room-102',
    roomNumber: 102,
    name: 'Room 102 - Valley Vista Balcony',
    categoryId: 'cat-1',
    categoryCode: 'deluxe_mountain',
    categoryName: 'Deluxe Mountain View with Balcony',
    floorLevel: 1,
    currentStatus: 'confirmed',
    housekeeping: 'clean',
    qrSecretToken: 'wp-qr-room102-token88',
    notes: 'Arriving today at 3:00 PM via NJP transfer car.',
  },
  {
    id: 'room-103',
    roomNumber: 103,
    name: 'Room 103 - Himalayan Mist Balcony',
    categoryId: 'cat-1',
    categoryCode: 'deluxe_mountain',
    categoryName: 'Deluxe Mountain View with Balcony',
    floorLevel: 1,
    currentStatus: 'available',
    housekeeping: 'clean',
    qrSecretToken: 'wp-qr-room103-token77',
    notes: 'Turnover completed. Available for walk-in or instant booking.',
  },
  {
    id: 'room-104',
    roomNumber: 104,
    name: 'Room 104 - Pine Canopy Balcony',
    categoryId: 'cat-2',
    categoryCode: 'deluxe_forest',
    categoryName: 'Deluxe Forest View with Balcony',
    floorLevel: 1,
    currentStatus: 'checked_in',
    housekeeping: 'light_refresh',
    qrSecretToken: 'wp-qr-room104-token66',
    notes: 'Family with 1 child. Strict Jain meal mandate.',
  },
  {
    id: 'room-201',
    roomNumber: 201,
    name: 'Room 201 - Summit Observation Suite',
    categoryId: 'cat-3',
    categoryCode: 'premium_suite',
    categoryName: 'Premium Mountain View Suites',
    floorLevel: 2,
    currentStatus: 'checked_in',
    housekeeping: 'clean',
    qrSecretToken: 'wp-qr-room201-token55',
    notes: 'Panoramic top floor suite. Fireplace prepped daily at 6 PM.',
  },
  {
    id: 'room-202',
    roomNumber: 202,
    name: 'Room 202 - Kanchenjunga View Suite',
    categoryId: 'cat-3',
    categoryCode: 'premium_suite',
    categoryName: 'Premium Mountain View Suites',
    floorLevel: 2,
    currentStatus: 'hold',
    housekeeping: 'clean',
    qrSecretToken: 'wp-qr-room202-token44',
    notes: 'Tentative hold until 6:00 PM awaiting advance deposit transfer.',
  },
  {
    id: 'room-203',
    roomNumber: 203,
    name: 'Room 203 - Cloud Peak Master Suite',
    categoryId: 'cat-3',
    categoryCode: 'premium_suite',
    categoryName: 'Premium Mountain View Suites',
    floorLevel: 2,
    currentStatus: 'confirmed',
    housekeeping: 'deep_clean_turnover',
    qrSecretToken: 'wp-qr-room203-token33',
    notes: 'Arriving tomorrow morning. Requested late checkout setup.',
  },
];

export const INITIAL_GUESTS: Guest[] = [
  {
    id: 'guest-1',
    fullName: 'Aarav Sharma',
    phone: '+91 99112 33445',
    email: 'aarav.sharma@example.com',
    idType: 'Aadhaar Card',
    idNumber: 'XXXX-XXXX-4812',
    idDocumentUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=400&q=80',
    dietaryPreferences: 'Vegetarian (No eggs, likes ginger honey tea)',
    hospitalityPreferences: 'Extra warm duvet, prefers morning wake-up call at 7:30 AM',
    whatsappNumber: '919911233445',
    totalLifetimeStays: 3,
  },
  {
    id: 'guest-2',
    fullName: 'Claire Dupont',
    phone: '+33 612 345678',
    email: 'claire.dupont@orange.fr',
    idType: 'Passport & Inner Line Permit',
    idNumber: 'FR-88291034',
    idDocumentUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=400&q=80',
    dietaryPreferences: 'Gluten-Free, loves black mountain coffee',
    hospitalityPreferences: 'Honeymoon arrangement: fresh pine cones, scented cedar candles',
    whatsappNumber: '33612345678',
    totalLifetimeStays: 1,
  },
  {
    id: 'guest-3',
    fullName: 'Vikram Mehta',
    phone: '+91 98201 54321',
    email: 'vikram.m@gmail.com',
    idType: 'Aadhaar Card',
    idNumber: 'XXXX-XXXX-9102',
    idDocumentUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    dietaryPreferences: 'Strict Jain (No root vegetables, no onion/garlic)',
    hospitalityPreferences: 'Thermos flask of boiled lukewarm water refilled twice daily',
    whatsappNumber: '919820154321',
    totalLifetimeStays: 2,
  },
  {
    id: 'guest-4',
    fullName: 'Sarah Jenkins',
    phone: '+44 7700 900123',
    email: 'sarah.j@outlook.com',
    idType: 'Passport',
    idNumber: 'GB-10293847',
    idDocumentUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    dietaryPreferences: 'Vegan, prefers oat/almond milk with tea',
    hospitalityPreferences: 'Quiet workspace corner, late checkout if possible',
    whatsappNumber: '447700900123',
    totalLifetimeStays: 1,
  },
  {
    id: 'guest-5',
    fullName: 'Marcus Vance',
    phone: '+44 7911 123456',
    email: 'marcus.vance@techventures.co.uk',
    idType: 'Driver License',
    idNumber: 'UK-DL-991244',
    idDocumentUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    dietaryPreferences: 'Severe Peanut & Tree Nut Allergy (Nut-Free Kitchen)',
    hospitalityPreferences: 'Fireplace firewood prepped daily at 6:00 PM',
    whatsappNumber: '447911123456',
    totalLifetimeStays: 4,
  },
  {
    id: 'guest-7',
    fullName: 'Dr. Rohan Malhotra',
    phone: '+91 98110 88776',
    email: 'rohan.malhotra@aiims.edu',
    idType: 'Aadhaar Card',
    idNumber: 'XXXX-XXXX-3341',
    idDocumentUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    dietaryPreferences: 'Non-Vegetarian, fond of authentic local Pahadi mutton curry',
    hospitalityPreferences: 'Early morning mountain trekking guide recommendation',
    whatsappNumber: '919811088776',
    totalLifetimeStays: 2,
  },
];

export const INITIAL_BOOKINGS: CRMBooking[] = [
  {
    id: 'bk-101',
    bookingReference: 'WP-2026-101',
    roomId: 'room-101',
    roomNumber: 101,
    roomName: 'Room 101 - Sunrise Mountain Balcony',
    guestId: 'guest-1',
    guest: INITIAL_GUESTS[0],
    checkInDate: '2026-09-14',
    checkOutDate: '2026-09-18',
    tapeStatus: 'checked_in',
    bookingStatus: 'checked_in',
    mealPlan: 'CP',
    adultsCount: 2,
    childrenCount: 0,
    roomRatePerNight: 4500,
    totalNights: 4,
    totalRoomAmount: 18000,
    specialRequests: 'Upper floor view, extra pillow set.',
    checkedInAt: '2026-09-14T14:30:00Z',
  },
  {
    id: 'bk-102',
    bookingReference: 'WP-2026-102',
    roomId: 'room-102',
    roomNumber: 102,
    roomName: 'Room 102 - Valley Vista Balcony',
    guestId: 'guest-2',
    guest: INITIAL_GUESTS[1],
    checkInDate: '2026-09-16',
    checkOutDate: '2026-09-19',
    tapeStatus: 'confirmed',
    bookingStatus: 'confirmed',
    mealPlan: 'MAP',
    adultsCount: 2,
    childrenCount: 1,
    roomRatePerNight: 4500,
    totalNights: 3,
    totalRoomAmount: 13500,
    specialRequests: 'Arriving Bagdogra flight ~1:30 PM. Honeymoon celebration.',
  },
  {
    id: 'bk-103',
    bookingReference: 'WP-2026-103',
    roomId: 'room-104',
    roomNumber: 104,
    roomName: 'Room 104 - Pine Canopy Balcony',
    guestId: 'guest-3',
    guest: INITIAL_GUESTS[2],
    checkInDate: '2026-09-15',
    checkOutDate: '2026-09-20',
    tapeStatus: 'checked_in',
    bookingStatus: 'checked_in',
    mealPlan: 'AP',
    adultsCount: 2,
    childrenCount: 1,
    roomRatePerNight: 4200,
    totalNights: 5,
    totalRoomAmount: 21000,
    specialRequests: 'Strict Jain preparation for all courses.',
    checkedInAt: '2026-09-15T15:10:00Z',
  },
  {
    id: 'bk-104',
    bookingReference: 'WP-2026-104',
    roomId: 'room-202',
    roomNumber: 202,
    roomName: 'Room 202 - Kanchenjunga View Suite',
    guestId: 'guest-4',
    guest: INITIAL_GUESTS[3],
    checkInDate: '2026-09-18',
    checkOutDate: '2026-09-22',
    tapeStatus: 'hold',
    bookingStatus: 'hold',
    mealPlan: 'EP',
    adultsCount: 2,
    childrenCount: 0,
    roomRatePerNight: 6500,
    totalNights: 4,
    totalRoomAmount: 26000,
    specialRequests: 'Holding room until advance UPI receipt shared.',
  },
  {
    id: 'bk-105',
    bookingReference: 'WP-2026-105',
    roomId: 'room-201',
    roomNumber: 201,
    roomName: 'Room 201 - Summit Observation Suite',
    guestId: 'guest-5',
    guest: INITIAL_GUESTS[4],
    checkInDate: '2026-09-13',
    checkOutDate: '2026-09-17',
    tapeStatus: 'checked_in',
    bookingStatus: 'checked_in',
    mealPlan: 'CP',
    adultsCount: 2,
    childrenCount: 0,
    roomRatePerNight: 6500,
    totalNights: 4,
    totalRoomAmount: 26000,
    specialRequests: 'Nut allergy caution. Checking out tomorrow morning.',
    checkedInAt: '2026-09-13T13:45:00Z',
  },
  {
    id: 'bk-107',
    bookingReference: 'WP-2026-107',
    roomId: 'room-203',
    roomNumber: 203,
    roomName: 'Room 203 - Cloud Peak Master Suite',
    guestId: 'guest-7',
    guest: INITIAL_GUESTS[5],
    checkInDate: '2026-09-17',
    checkOutDate: '2026-09-21',
    tapeStatus: 'confirmed',
    bookingStatus: 'confirmed',
    mealPlan: 'MAP',
    adultsCount: 2,
    childrenCount: 0,
    roomRatePerNight: 6500,
    totalNights: 4,
    totalRoomAmount: 26000,
    specialRequests: 'Arriving early morning by NJP car.',
  },
];

export const INITIAL_FOLIOS: GuestFolio[] = [
  {
    id: 'fol-101',
    bookingId: 'bk-101',
    guestId: 'guest-1',
    guestName: 'Aarav Sharma',
    roomNumber: 101,
    roomName: 'Room 101 - Sunrise Mountain Balcony',
    folioNumber: 'FOL-2026-101',
    status: 'open',
    totalRoomCharges: 18000,
    totalFbCharges: 1650,
    totalAddonCharges: 4200,
    totalTax: 1192.5,
    discountAmount: 0,
    netPayable: 25042.5,
    totalPaid: 15000,
    balanceDue: 10042.5,
    charges: [
      {
        id: 'chg-101-1',
        folioId: 'fol-101',
        category: 'room_tariff',
        chargeStatus: 'posted',
        title: 'Room Tariff - 4 Nights (Sunrise Mountain Balcony)',
        amount: 18000,
        sourceReferenceType: 'booking',
        sourceReferenceId: 'bk-101',
        postedAt: '2026-09-14T14:35:00Z',
      },
      {
        id: 'chg-101-2',
        folioId: 'fol-101',
        category: 'food_beverage',
        chargeStatus: 'posted',
        title: 'QR Order #ORD-101 - Steamed Momos & Darjeeling Tea x2',
        amount: 650,
        sourceReferenceType: 'food_order',
        sourceReferenceId: 'ord-101',
        postedAt: '2026-09-14T19:20:00Z',
      },
      {
        id: 'chg-101-3',
        folioId: 'fol-101',
        category: 'food_beverage',
        chargeStatus: 'pending',
        title: 'QR Order #ORD-103 - Pahadi Kadi Rice & Tingmo',
        amount: 1000,
        sourceReferenceType: 'food_order',
        sourceReferenceId: 'ord-103',
        postedAt: '2026-09-15T13:40:00Z',
      },
      {
        id: 'chg-101-4',
        folioId: 'fol-101',
        category: 'transport_transfer',
        chargeStatus: 'posted',
        title: 'Transfer: Darjeeling to NJP Railway (Sedan)',
        amount: 4200,
        sourceReferenceType: 'transport_request',
        sourceReferenceId: 'dsp-501',
        postedAt: '2026-09-15T16:00:00Z',
      },
    ],
    payments: [
      {
        id: 'pay-101-1',
        folioId: 'fol-101',
        amount: 15000,
        paymentMethod: 'upi',
        transactionReference: 'UPI-REF-9928172034',
        receiptNotes: 'Advance 50% deposit received via GooglePay',
        collectedAt: '2026-09-10T11:20:00Z',
        collectedByName: 'Manager - Rinchen',
      },
    ],
  },
  {
    id: 'fol-103',
    bookingId: 'bk-103',
    guestId: 'guest-3',
    guestName: 'Vikram Mehta',
    roomNumber: 104,
    roomName: 'Room 104 - Pine Canopy Balcony',
    folioNumber: 'FOL-2026-103',
    status: 'open',
    totalRoomCharges: 21000,
    totalFbCharges: 2100,
    totalAddonCharges: 1800,
    totalTax: 1245,
    discountAmount: 1000,
    netPayable: 25145,
    totalPaid: 20000,
    balanceDue: 5145,
    charges: [
      {
        id: 'chg-103-1',
        folioId: 'fol-103',
        category: 'room_tariff',
        chargeStatus: 'posted',
        title: 'Room Tariff - 5 Nights (Pine Canopy Balcony)',
        amount: 21000,
        sourceReferenceType: 'booking',
        sourceReferenceId: 'bk-103',
        postedAt: '2026-09-15T15:15:00Z',
      },
      {
        id: 'chg-103-2',
        folioId: 'fol-103',
        category: 'food_beverage',
        chargeStatus: 'posted',
        title: 'Special Jain High-Tea & Snacks for 4',
        amount: 2100,
        sourceReferenceType: 'food_order',
        postedAt: '2026-09-15T18:00:00Z',
      },
      {
        id: 'chg-103-3',
        folioId: 'fol-103',
        category: 'vehicle_rental',
        chargeStatus: 'posted',
        title: 'Rental: Royal Enfield Classic 350 (1 Day)',
        amount: 1800,
        sourceReferenceType: 'transport_request',
        postedAt: '2026-09-16T09:00:00Z',
      },
    ],
    payments: [
      {
        id: 'pay-103-1',
        folioId: 'fol-103',
        amount: 20000,
        paymentMethod: 'bank_transfer',
        transactionReference: 'NEFT-HDFC-991823',
        receiptNotes: 'Advance payment received',
        collectedAt: '2026-09-12T14:10:00Z',
        collectedByName: 'Manager - Rinchen',
      },
    ],
  },
  {
    id: 'fol-105',
    bookingId: 'bk-105',
    guestId: 'guest-5',
    guestName: 'Marcus Vance',
    roomNumber: 5,
    roomName: 'Room 5 - Pine Haven Deluxe',
    folioNumber: 'FOL-2026-105',
    status: 'open',
    totalRoomCharges: 15200,
    totalFbCharges: 1450,
    totalAddonCharges: 0,
    totalTax: 832.5,
    discountAmount: 0,
    netPayable: 17482.5,
    totalPaid: 15200,
    balanceDue: 2282.5,
    charges: [
      {
        id: 'chg-105-1',
        folioId: 'fol-105',
        category: 'room_tariff',
        chargeStatus: 'posted',
        title: 'Room Tariff - 4 Nights (Pine Haven Deluxe)',
        amount: 15200,
        sourceReferenceType: 'booking',
        sourceReferenceId: 'bk-105',
        postedAt: '2026-09-13T13:50:00Z',
      },
      {
        id: 'chg-105-2',
        folioId: 'fol-105',
        category: 'food_beverage',
        chargeStatus: 'posted',
        title: 'Nut-Free Tibetan Thukpa & Herbal Infusion x2',
        amount: 1450,
        sourceReferenceType: 'food_order',
        postedAt: '2026-09-14T20:15:00Z',
      },
    ],
    payments: [
      {
        id: 'pay-105-1',
        folioId: 'fol-105',
        amount: 15200,
        paymentMethod: 'cash',
        transactionReference: 'CASH-REC-0041',
        receiptNotes: 'Cash collected at check-in counter',
        collectedAt: '2026-09-13T14:00:00Z',
        collectedByName: 'Owner - Tenzing',
      },
    ],
  },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // Beverages & Hot Brews
  {
    id: 'menu-1',
    categoryId: 'bev',
    categoryName: 'Beverages & Hot Brews',
    name: 'Darjeeling First Flush Autumn Tea',
    description: 'Fresh artisanal single-estate Makaibari Muscatel tea served in earthen clay kettle with Himalayan wildflower honey.',
    price: 180,
    itemType: 'beverage',
    isAvailable: true,
    isLateNightEligible: true,
    prepTimeMinutes: 10,
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-2',
    categoryId: 'bev',
    categoryName: 'Beverages & Hot Brews',
    name: 'Spiced Mountain Masala Chai',
    description: 'Hand-ground cinnamon, green cardamom, fresh hill ginger, and organic farm cow milk boiled to aromatic perfection.',
    price: 120,
    itemType: 'beverage',
    isAvailable: true,
    isLateNightEligible: true,
    prepTimeMinutes: 12,
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-3',
    categoryId: 'bev',
    categoryName: 'Beverages & Hot Brews',
    name: 'Himalayan Badam & Kesar Milk',
    description: 'Rich warm whole milk simmered with Kashmiri saffron strands, crushed almonds, and crushed pistachio.',
    price: 240,
    itemType: 'beverage',
    isAvailable: true,
    isLateNightEligible: true,
    prepTimeMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=400&q=80',
  },
  // Himalayan Snacks
  {
    id: 'menu-4',
    categoryId: 'snack',
    categoryName: 'Himalayan Snacks',
    name: 'Authentic Steamed Veg Momos (8 Pcs)',
    description: 'Delicate hand-wrapped dumplings stuffed with finely minced farm cabbage, paneer, and spring scallions. Served with spicy fire-roasted tomato dalle chilli chutney.',
    price: 260,
    itemType: 'snack',
    isAvailable: true,
    isLateNightEligible: true,
    prepTimeMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-5',
    categoryId: 'snack',
    categoryName: 'Himalayan Snacks',
    name: 'Steamed Chicken Kothey Momos (8 Pcs)',
    description: 'Juicy local organic poultry mince dumplings, pan-seared on bottom for a golden crunch, accompanied by fragrant broth and sesame dipping sauce.',
    price: 320,
    itemType: 'snack',
    isAvailable: true,
    isLateNightEligible: false,
    prepTimeMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-6',
    categoryId: 'snack',
    categoryName: 'Himalayan Snacks',
    name: 'Crispy Mountain Potato Wedges & Dalle Mayo',
    description: 'High-altitude organic red potatoes dusted with mountain herbs and smoked paprika, served with homemade Himalayan chilli mayo.',
    price: 220,
    itemType: 'snack',
    isAvailable: true,
    isLateNightEligible: true,
    prepTimeMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=400&q=80',
  },
  // Traditional Mains
  {
    id: 'menu-7',
    categoryId: 'main',
    categoryName: 'Traditional Mains',
    name: 'Pahadi Kadi & Steamed Brown Rice Thali',
    description: 'Tangy slow-simmered Himalayan yogurt stew tempered with mustard seeds and mountain fenugreek, served with fragrant local red rice, seasonal greens, and homemade pickles.',
    price: 380,
    itemType: 'main',
    isAvailable: true,
    isLateNightEligible: false,
    prepTimeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-8',
    categoryId: 'main',
    categoryName: 'Traditional Mains',
    name: 'Himalayan Country Chicken Curry & Hot Phulkas',
    description: 'Free-range country chicken slow-braised in an artisanal stone-ground gravy of hill spices, served with 4 ghee-brushed phulkas and fresh mint salad.',
    price: 490,
    itemType: 'main',
    isAvailable: true,
    isLateNightEligible: false,
    prepTimeMinutes: 35,
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-9',
    categoryId: 'main',
    categoryName: 'Traditional Mains',
    name: 'Tibetan Vegetable Thukpa with Tingmo Bread',
    description: 'Hearty steaming bowl of handmade wheat noodles in a ginger-garlic-cilantro aromatic broth with bok choy and tofu, paired with fluffy flower-shaped steamed Tingmo bread.',
    price: 350,
    itemType: 'main',
    isAvailable: true,
    isLateNightEligible: false,
    prepTimeMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: 'menu-10',
    categoryId: 'main',
    categoryName: 'Traditional Mains',
    name: 'Bhutanese Ema Datshi & Red Rice',
    description: 'Traditional stew made with organic mountain chilis and artisanal yak cheese, rich and comforting, served with steaming Bhutanese red rice.',
    price: 420,
    itemType: 'main',
    isAvailable: false, // Out of stock to test kitchen stock toggle!
    isLateNightEligible: false,
    prepTimeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=400&q=80',
  },
];

export const INITIAL_TRANSFER_ROUTES: TransferRoute[] = [
  {
    id: 'route-1',
    title: 'Darjeeling to NJP Railway Station / Bagdogra Airport (IXB)',
    origin: 'Savera Homestay, Darjeeling',
    destination: 'NJP Railway Station or Bagdogra Airport',
    priceWagonR: 3500,
    priceSedan: 4200,
    priceSUV: 5500,
    estimatedDurationHours: 3.5,
    isActive: true,
    modifiers: [
      {
        id: 'mod-1',
        routeId: 'route-1',
        name: 'Via Mirik Lake, Pine Forest & Sumendu Lake Promenade',
        extraCharge: 1500,
        extraDurationHours: 2.5,
      },
      {
        id: 'mod-2',
        routeId: 'route-1',
        name: 'Via Kurseong Eagle\'s Crag & Makaibari Tea Garden Tasting',
        extraCharge: 1200,
        extraDurationHours: 2.0,
      },
    ],
  },
  {
    id: 'route-2',
    title: 'Darjeeling to Gangtok (Sikkim)',
    origin: 'Savera Homestay, Darjeeling',
    destination: 'Gangtok Hotel / MG Marg',
    priceWagonR: 4800,
    priceSedan: 5600,
    priceSUV: 7200,
    estimatedDurationHours: 4.5,
    isActive: true,
    modifiers: [
      {
        id: 'mod-3',
        routeId: 'route-2',
        name: 'Via Namchi Char Dham & Ravangla Buddha Park Heritage Tour',
        extraCharge: 2200,
        extraDurationHours: 3.0,
      },
      {
        id: 'mod-4',
        routeId: 'route-2',
        name: 'Via Teesta River Confluence & Lovers Meet Viewpoint',
        extraCharge: 900,
        extraDurationHours: 1.5,
      },
    ],
  },
];

export const INITIAL_RENTAL_VEHICLES: RentalVehicle[] = [
  {
    id: 'veh-1',
    vehicleName: 'Royal Enfield Classic 350 (Stealth Black)',
    vehicleType: 'bike',
    ratePerDay: 1800,
    depositRequired: 2000,
    isAvailable: true,
  },
  {
    id: 'veh-2',
    vehicleName: 'Royal Enfield Himalayan 450 (Kamet White)',
    vehicleType: 'bike',
    ratePerDay: 2200,
    depositRequired: 2500,
    isAvailable: true,
  },
  {
    id: 'veh-3',
    vehicleName: 'Honda Activa 6G (Matte Axis Grey)',
    vehicleType: 'scooty',
    ratePerDay: 900,
    depositRequired: 1000,
    isAvailable: true,
  },
];

export const INITIAL_DISPATCH_REQUESTS: TransportRequest[] = [
  {
    id: 'dsp-501',
    requestNumber: 'DSP-501',
    roomId: 'room-1',
    roomNumber: 1,
    roomName: 'Room 1 - Pine Haven Suite',
    bookingId: 'bk-101',
    folioId: 'fol-101',
    guestName: 'Aarav Sharma',
    guestContactPhone: '+91 99112 33445',
    serviceType: 'point_to_point',
    routeId: 'route-1',
    routeTitle: 'Darjeeling to NJP Railway Station',
    vehicleTier: 'sedan',
    selectedModifiers: [
      { name: 'Via Mirik Lake & Tea Gardens', charge: 1500 },
    ],
    pickupDatetime: '2026-09-18T09:00:00Z',
    pickupLocation: 'Homestay Main Driveway',
    destinationNotes: 'Drop at NJP Platform 1 for Vande Bharat Express at 3:00 PM.',
    quotedPrice: 5700,
    vendorCost: 4500,
    homestayCommission: 1200,
    dispatchStatus: 'confirmed_dispatched',
    assignedDriverName: 'Tashi Bhutia',
    assignedDriverPhone: '+91 98320 11223',
    vehiclePlateNumber: 'WB 74 BK 8812',
    confirmedAt: '2026-09-15T16:00:00Z',
    chargePostedToFolio: true,
    createdAt: '2026-09-15T15:30:00Z',
  },
  {
    id: 'dsp-502',
    requestNumber: 'DSP-502',
    roomId: 'room-104',
    roomNumber: 104,
    roomName: 'Room 104 - Pine Canopy Balcony',
    bookingId: 'bk-103',
    folioId: 'fol-103',
    guestName: 'Vikram Mehta',
    guestContactPhone: '+91 98201 54321',
    serviceType: 'vehicle_rental',
    rentalVehicleId: 'veh-1',
    rentalVehicleName: 'Royal Enfield Classic 350 (Stealth Black)',
    selectedModifiers: [],
    pickupDatetime: '2026-09-17T08:30:00Z',
    returnDatetime: '2026-09-18T08:30:00Z',
    pickupLocation: 'Homestay Parking Lot',
    destinationNotes: 'Self-ride to Tiger Hill & Batasia Loop.',
    quotedPrice: 1800,
    vendorCost: 1200,
    homestayCommission: 600,
    dispatchStatus: 'pending_confirmation',
    chargePostedToFolio: true,
    createdAt: '2026-09-16T11:45:00Z',
  },
];

export const INITIAL_HOUSEKEEPING_TASKS: HousekeepingTask[] = [
  {
    id: 'hk-1',
    roomId: 'room-203',
    roomNumber: 203,
    roomName: 'Room 203 - Cloud Peak Master Suite',
    scheduleDate: '2026-09-16',
    taskType: 'deep_clean_turnover',
    status: 'in_progress',
    assignedToName: 'Dawa Lepcha',
    priority: 'high',
    checklist: {
      linens_changed: true,
      toiletries_restocked: true,
      fireplace_prepped: false,
      balcony_cleaned: false,
    },
    notes: 'Guest checking in tomorrow morning. Thorough cedar polish needed.',
  },
  {
    id: 'hk-2',
    roomId: 'room-104',
    roomNumber: 104,
    roomName: 'Room 104 - Pine Canopy Balcony',
    scheduleDate: '2026-09-16',
    taskType: 'light_refresh',
    status: 'completed',
    assignedToName: 'Sunita Pradhan',
    priority: 'normal',
    checklist: {
      linens_changed: false,
      toiletries_restocked: true,
      fireplace_prepped: true,
      balcony_cleaned: true,
    },
    notes: 'Afternoon daily refresh completed. Water flask replenished.',
    completedAt: '2026-09-16T14:15:00Z',
  },
  {
    id: 'hk-3',
    roomId: 'room-201',
    roomNumber: 201,
    roomName: 'Room 201 - Summit Observation Suite',
    scheduleDate: '2026-09-16',
    taskType: 'light_refresh',
    status: 'pending',
    assignedToName: 'Sunita Pradhan',
    priority: 'normal',
    checklist: {
      linens_changed: false,
      toiletries_restocked: false,
      fireplace_prepped: false,
      balcony_cleaned: false,
    },
    notes: 'Evening refresh requested at 5:00 PM when guest finishes remote work.',
  },
  {
    id: 'hk-4',
    roomId: 'room-103',
    roomNumber: 103,
    roomName: 'Room 103 - Himalayan Mist Balcony',
    scheduleDate: '2026-09-16',
    taskType: 'maintenance_inspection',
    status: 'in_progress',
    assignedToName: 'Pemba Plumber',
    priority: 'urgent',
    checklist: {
      linens_changed: false,
      toiletries_restocked: false,
      fireplace_prepped: false,
      balcony_cleaned: false,
    },
    notes: 'Geyser replacement and water pressure validation in progress.',
  },
];

export const INITIAL_FOOD_ORDERS: any[] = [
  {
    id: 'ord-101',
    orderNumber: 'ORD-101',
    roomId: 'room-1',
    roomNumber: 1,
    roomName: 'Room 1 - Pine Haven Suite',
    bookingId: 'bk-101',
    folioId: 'fol-101',
    guestName: 'Aarav Sharma',
    status: 'delivered',
    specialInstructions: 'Extra spicy dalle chutney on the side please.',
    subtotal: 650,
    deliveryCharge: 0,
    totalAmount: 650,
    chargePostedToFolio: true,
    whatsappNotificationSent: true,
    items: [
      {
        id: 'oi-1',
        menuItemId: 'menu-4',
        itemName: 'Authentic Steamed Veg Momos',
        unitPrice: 260,
        quantity: 1,
        lineTotal: 260,
        itemNotes: 'Extra spicy',
      },
      {
        id: 'oi-2',
        menuItemId: 'menu-1',
        itemName: 'Darjeeling First Flush Autumn Tea',
        unitPrice: 180,
        quantity: 2,
        lineTotal: 360,
      },
      {
        id: 'oi-3',
        menuItemId: 'menu-2',
        itemName: 'Spiced Mountain Masala Chai',
        unitPrice: 120,
        quantity: 1,
        lineTotal: 120,
      },
    ],
    createdAt: '2026-09-14T19:20:00Z',
  },
  {
    id: 'ord-103',
    orderNumber: 'ORD-103',
    roomId: 'room-1',
    roomNumber: 1,
    roomName: 'Room 1 - Pine Haven Suite',
    bookingId: 'bk-101',
    folioId: 'fol-101',
    guestName: 'Aarav Sharma',
    status: 'accepted_kitchen',
    specialInstructions: 'Mild spices, warm ginger tea before food.',
    subtotal: 1000,
    deliveryCharge: 0,
    totalAmount: 1000,
    chargePostedToFolio: true,
    whatsappNotificationSent: true,
    items: [
      {
        id: 'oi-4',
        menuItemId: 'menu-7',
        itemName: 'Pahadi Kadi & Steamed Brown Rice Thali',
        unitPrice: 380,
        quantity: 2,
        lineTotal: 760,
      },
      {
        id: 'oi-5',
        menuItemId: 'menu-3',
        itemName: 'Himalayan Badam & Kesar Milk',
        unitPrice: 240,
        quantity: 1,
        lineTotal: 240,
      },
    ],
    createdAt: '2026-09-16T12:30:00Z',
  },
  {
    id: 'ord-104',
    orderNumber: 'ORD-104',
    roomId: 'room-104',
    roomNumber: 104,
    roomName: 'Room 104 - Pine Canopy Balcony',
    bookingId: 'bk-103',
    folioId: 'fol-103',
    guestName: 'Vikram Mehta',
    status: 'pending',
    specialInstructions: 'STRICT JAIN: No root vegetables, no onion, garlic. Use rock salt.',
    subtotal: 780,
    deliveryCharge: 0,
    totalAmount: 780,
    chargePostedToFolio: true,
    whatsappNotificationSent: true,
    items: [
      {
        id: 'oi-6',
        menuItemId: 'menu-4',
        itemName: 'Authentic Steamed Veg Momos',
        unitPrice: 260,
        quantity: 2,
        lineTotal: 520,
        itemNotes: 'Strict Jain preparation',
      },
      {
        id: 'oi-7',
        menuItemId: 'menu-2',
        itemName: 'Spiced Mountain Masala Chai',
        unitPrice: 120,
        quantity: 2,
        lineTotal: 240,
        itemNotes: 'No ginger, only cardamom & cinnamon',
      },
    ],
    createdAt: '2026-09-16T14:40:00Z',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    expenseDate: '2026-09-15',
    amount: 8450,
    paymentMethod: 'cash',
    masterCategory: 'groceries',
    subTag: 'Produce & Dairy',
    vendorPayee: 'Darjeeling Local Farmers Co-op',
    description: 'Weekly organic vegetables, farm fresh milk, butter, and cow cheese for kitchen mandate',
    billReceiptUrl: 'https://images.unsplash.com/photo-1554415707-9e4426d429d2?auto=format&fit=crop&w=400&q=80',
    loggedByName: 'Admin - Tenzing',
    createdAt: '2026-09-15T18:00:00Z',
  },
  {
    id: 'exp-2',
    expenseDate: '2026-09-14',
    amount: 3200,
    paymentMethod: 'upi',
    masterCategory: 'utilities',
    subTag: 'LPG Commercial Cylinders',
    vendorPayee: 'Indane Gas Agency Kurseong',
    description: '2 commercial LPG cylinders refilled for homestay kitchen and fireplace boilers',
    billReceiptUrl: 'https://images.unsplash.com/photo-1554415707-9e4426d429d2?auto=format&fit=crop&w=400&q=80',
    loggedByName: 'Admin - Tenzing',
    createdAt: '2026-09-14T11:30:00Z',
  },
  {
    id: 'exp-3',
    expenseDate: '2026-09-12',
    amount: 14500,
    paymentMethod: 'bank_transfer',
    masterCategory: 'staff_payroll',
    subTag: 'Kitchen & Service Stipend (Mid-Month)',
    vendorPayee: 'Kitchen Chef Sonam & Stewards',
    description: 'Mid-month staff advance stipend and bonus disbursement',
    loggedByName: 'Admin - Tenzing',
    createdAt: '2026-09-12T16:00:00Z',
  },
  {
    id: 'exp-4',
    expenseDate: '2026-09-10',
    amount: 4500,
    paymentMethod: 'upi',
    masterCategory: 'transport_vendor',
    subTag: 'Local Taxi Consortium',
    vendorPayee: 'Darjeeling Hill Drivers Association',
    description: 'Payment for NJP transfer driver assignment (Booking WP-2026-101)',
    billReceiptUrl: 'https://images.unsplash.com/photo-1554415707-9e4426d429d2?auto=format&fit=crop&w=400&q=80',
    loggedByName: 'Admin - Tenzing',
    createdAt: '2026-09-10T19:00:00Z',
  },
  {
    id: 'exp-5',
    expenseDate: '2026-09-08',
    amount: 2800,
    paymentMethod: 'cash',
    masterCategory: 'maintenance',
    subTag: 'Plumbing & Geyser Parts',
    vendorPayee: 'Singamari Hardware & Electric',
    description: 'High-pressure valve and heating element replacement for Room 6 geyser',
    billReceiptUrl: 'https://images.unsplash.com/photo-1554415707-9e4426d429d2?auto=format&fit=crop&w=400&q=80',
    loggedByName: 'Admin - Tenzing',
    createdAt: '2026-09-08T10:15:00Z',
  },
  {
    id: 'exp-6',
    expenseDate: '2026-09-05',
    amount: 3400,
    paymentMethod: 'bank_transfer',
    masterCategory: 'utilities',
    subTag: 'Starlink High-Speed Internet',
    vendorPayee: 'Starlink India Telecommunications',
    description: 'Monthly high-speed satellite broadband plan subscription for estate and guest Wi-Fi',
    loggedByName: 'Admin - Tenzing',
    createdAt: '2026-09-05T09:00:00Z',
  },
];

export const INITIAL_STAFF_ACCOUNTS: StaffAccount[] = [
  {
    id: 'staff-admin',
    email: 'admin@saverahomestay.com',
    password: 'admin123',
    fullName: 'Savera Admin (Owner)',
    phone: '+91 81012 98882',
    role: 'admin',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
];


export const INITIAL_SEASONAL_DATE_RANGES: SeasonalDateRange[] = [
  {
    id: 'season-1',
    name: 'Summer Peak Holidays 2026',
    seasonType: 'season',
    startDate: '2026-05-01',
    endDate: '2026-06-30',
    description: 'High summer demand, warm mountain days and crisp evenings.',
  },
  {
    id: 'season-2',
    name: 'Autumn & Durga Puja / Diwali Peak',
    seasonType: 'season',
    startDate: '2026-10-01',
    endDate: '2026-11-15',
    description: 'Festive mountain holiday season with crystal clear Himalayan views.',
  },
  {
    id: 'season-3',
    name: 'Christmas & New Year Gala Peak',
    seasonType: 'season',
    startDate: '2026-12-20',
    endDate: '2027-01-05',
    description: 'Winter festive peak with live bonfires and celebration dinners.',
  },
  {
    id: 'season-4',
    name: 'Monsoon Green Season (Off-Season)',
    seasonType: 'off_season',
    startDate: '2026-07-15',
    endDate: '2026-08-31',
    description: 'Lush greenery, misty mountain waterfalls with relaxing discounted tariffs.',
  },
  {
    id: 'season-5',
    name: 'Post-Winter Lean Period (Off-Season)',
    seasonType: 'off_season',
    startDate: '2026-01-15',
    endDate: '2026-02-28',
    description: 'Quiet workation and budget solitude retreat months.',
  },
];

export const INITIAL_ROOM_SEASONAL_TARIFFS: Record<string, RoomSeasonalTariffs> = {
  // Deluxe Mountain View with Balcony (Rooms 101, 102, 103)
  'room-101': {
    regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 },
    season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 },
    offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 },
    weekendSurchargePercent: 10,
  },
  'room-102': {
    regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 },
    season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 },
    offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 },
    weekendSurchargePercent: 10,
  },
  'room-103': {
    regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 },
    season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 },
    offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 },
    weekendSurchargePercent: 10,
  },

  // Deluxe Forest View with Balcony (Room 104)
  'room-104': {
    regular: { EP: 4200, CP: 4800, MAP: 5800, AP: 6800 },
    season: { EP: 5400, CP: 6100, MAP: 7200, AP: 8300 },
    offSeason: { EP: 3500, CP: 4000, MAP: 4800, AP: 5600 },
    weekendSurchargePercent: 10,
  },

  // Premium Mountain View Suites (Rooms 201, 202, 203)
  'room-201': {
    regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 },
    season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 },
    offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 },
    weekendSurchargePercent: 12,
  },
  'room-202': {
    regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 },
    season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 },
    offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 },
    weekendSurchargePercent: 12,
  },
  'room-203': {
    regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 },
    season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 },
    offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 },
    weekendSurchargePercent: 12,
  },

  // Fallbacks for legacy references
  'room-1': { regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 }, season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 }, offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 }, weekendSurchargePercent: 10 },
  'room-2': { regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 }, season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 }, offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 }, weekendSurchargePercent: 10 },
  'room-3': { regular: { EP: 4500, CP: 5200, MAP: 6200, AP: 7200 }, season: { EP: 5800, CP: 6600, MAP: 7800, AP: 8900 }, offSeason: { EP: 3800, CP: 4300, MAP: 5100, AP: 5900 }, weekendSurchargePercent: 10 },
  'room-4': { regular: { EP: 4200, CP: 4800, MAP: 5800, AP: 6800 }, season: { EP: 5400, CP: 6100, MAP: 7200, AP: 8300 }, offSeason: { EP: 3500, CP: 4000, MAP: 4800, AP: 5600 }, weekendSurchargePercent: 10 },
  'room-5': { regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 }, season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 }, offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 }, weekendSurchargePercent: 12 },
  'room-6': { regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 }, season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 }, offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 }, weekendSurchargePercent: 12 },
  'room-7': { regular: { EP: 6500, CP: 7400, MAP: 8600, AP: 9800 }, season: { EP: 8500, CP: 9600, MAP: 11000, AP: 12500 }, offSeason: { EP: 5200, CP: 5900, MAP: 6900, AP: 7900 }, weekendSurchargePercent: 12 },
};

